package cloudflareredirect

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const (
	includeBegin = "# msf-cloudflare-redirect include begin"
	includeEnd   = "# msf-cloudflare-redirect include end"
	directBegin  = "# msf-cloudflare-redirect direct begin"
	directEnd    = "# msf-cloudflare-redirect direct end"
)

type ApplyResult struct {
	DomainCount int
	IPv4Count   int
	IPv6Count   int
	Restarted   bool
}

func Apply(ctx context.Context, dataDir string, cfg Config, st State) (ApplyResult, error) {
	if !cfg.Enabled {
		return ApplyResult{}, errors.New("cloudflare redirect is disabled in cfyouxuan.yaml")
	}
	domains, warnings := LoadDomains(ctx, cfg)
	if len(domains) == 0 {
		_ = writeRuleFile(dataDir, nil, nil, nil)
		_ = RemoveInjection(ctx, dataDir, cfg.Apply.RestartMosDNS.Enabled(true))
		st.DomainCount = 0
		st.Injected = false
		st.LastApplyAt = time.Now()
		st.LastError = joinWarnings(warnings, "no redirect domains configured")
		_ = SaveState(dataDir, st)
		return ApplyResult{}, errors.New("no redirect domains configured; add rules.manual or enabled rules.subscriptions in cfyouxuan.yaml")
	}
	v4 := selectedIPs(st.BestIPv4)
	v6 := selectedIPs(st.BestIPv6)
	if !cfg.Apply.RewriteA {
		v4 = nil
	}
	if !cfg.Apply.RewriteAAAA.Enabled(cfg.Scan.IPv6.Enabled.Enabled(autoIPv6Enabled(dataDir))) {
		v6 = nil
	}
	if len(v4) == 0 && len(v6) == 0 {
		return ApplyResult{}, errors.New("no Cloudflare redirect IPs available; run msf cloudflare-redirect scan first")
	}
	if err := writeRuleFile(dataDir, domains, v4, v6); err != nil {
		return ApplyResult{}, err
	}
	if err := writeSubConfig(dataDir); err != nil {
		return ApplyResult{}, err
	}
	if err := injectMosDNSConfig(dataDir); err != nil {
		return ApplyResult{}, err
	}
	st.DomainCount = len(domains)
	st.Injected = true
	st.LastApplyAt = time.Now()
	st.LastError = joinWarnings(warnings)
	if err := SaveState(dataDir, st); err != nil {
		return ApplyResult{}, err
	}
	result := ApplyResult{DomainCount: len(domains), IPv4Count: len(v4), IPv6Count: len(v6)}
	if cfg.Apply.RestartMosDNS.Enabled(true) {
		restarted, err := RestartMosDNSIfRunning(ctx, dataDir)
		result.Restarted = restarted
		if err != nil {
			return result, err
		}
	}
	return result, nil
}

func joinWarnings(warnings []string, extra ...string) string {
	var parts []string
	for _, warning := range warnings {
		if strings.TrimSpace(warning) != "" {
			parts = append(parts, warning)
		}
	}
	for _, item := range extra {
		if strings.TrimSpace(item) != "" {
			parts = append(parts, item)
		}
	}
	return strings.Join(parts, "; ")
}

func RemoveInjection(ctx context.Context, dataDir string, restart bool) error {
	path := MosDNSConfigPath(dataDir)
	b, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}
	content := removeMarkedBlock(string(b), includeBegin, includeEnd)
	content = removeMarkedBlock(content, directBegin, directEnd)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	st, _ := LoadState(dataDir)
	st.Injected = false
	st.LastApplyAt = time.Now()
	_ = SaveState(dataDir, st)
	if restart {
		_, err = RestartMosDNSIfRunning(ctx, dataDir)
	}
	return err
}

func selectedIPs(results []ScanResult) []string {
	var out []string
	for _, result := range results {
		if strings.TrimSpace(result.IP) != "" {
			out = append(out, strings.TrimSpace(result.IP))
		}
	}
	return out
}

func writeRuleFile(dataDir string, domains, v4, v6 []string) error {
	var b4 strings.Builder
	var b6 strings.Builder
	b4.WriteString("# generated by msf cloudflare-redirect; do not edit here\n")
	b6.WriteString("# generated by msf cloudflare-redirect; do not edit here\n")
	for _, domain := range domains {
		for _, ip := range v4 {
			b4.WriteString(domain)
			b4.WriteByte(' ')
			b4.WriteString(ip)
			b4.WriteByte('\n')
		}
		for _, ip := range v6 {
			b6.WriteString(domain)
			b6.WriteByte(' ')
			b6.WriteString(ip)
			b6.WriteByte('\n')
		}
	}
	if err := os.MkdirAll(filepath.Dir(RulePath(dataDir)), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(RulePath(dataDir), []byte(b4.String()), 0o644); err != nil {
		return err
	}
	return os.WriteFile(RulePathV6(dataDir), []byte(b6.String()), 0o644)
}

func writeSubConfig(dataDir string) error {
	content := `plugins:
  - tag: cloudflare_redirect_rewrite_v4
    type: rewrite
    args:
      files:
        - "rule/cloudflare_redirect.txt"
      dns: 127.0.0.1:2222

  - tag: cloudflare_redirect_rewrite_v6
    type: rewrite
    args:
      files:
        - "rule/cloudflare_redirect_v6.txt"
      dns: 127.0.0.1:2222

  - tag: sequence_cloudflare_redirect
    type: sequence
    args:
      - matches: qtype 1
        exec: $cloudflare_redirect_rewrite_v4
      - matches: qtype 28
        exec: $cloudflare_redirect_rewrite_v6
`
	path := SubConfigPath(dataDir)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func injectMosDNSConfig(dataDir string) error {
	path := MosDNSConfigPath(dataDir)
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	content := removeMarkedBlock(string(b), includeBegin, includeEnd)
	content = removeMarkedBlock(content, directBegin, directEnd)
	content, err = injectInclude(content)
	if err != nil {
		return err
	}
	content, err = injectDirectCall(content)
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func injectInclude(content string) (string, error) {
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if strings.Contains(line, `"sub_config/rule_set.yaml"`) {
			insert := []string{
				"  " + includeBegin,
				`  - "sub_config/cloudflare_redirect.yaml" # Cloudflare优选，仅在直连客户端分支调用`,
				"  " + includeEnd,
			}
			lines = insertLines(lines, i+1, insert)
			return strings.Join(lines, "\n"), nil
		}
	}
	return "", errors.New("cannot find MosDNS include anchor sub_config/rule_set.yaml")
}

func injectDirectCall(content string) (string, error) {
	lines := strings.Split(content, "\n")
	inserted := 0
	for i := 0; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) != "- matches: fast_mark 39" {
			continue
		}
		for j := i + 1; j < len(lines) && j < i+12; j++ {
			if strings.TrimSpace(lines[j]) == "- $sequence_local" {
				indent := leadingWhitespace(lines[j])
				insert := []string{
					indent + directBegin,
					indent + "- $sequence_cloudflare_redirect",
					indent + directEnd,
				}
				lines = insertLines(lines, j, insert)
				inserted++
				i = j + len(insert)
				break
			}
		}
	}
	if inserted == 0 {
		return "", errors.New("cannot find fast_mark39 direct client branch in MosDNS config")
	}
	return strings.Join(lines, "\n"), nil
}

func removeMarkedBlock(content, begin, end string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	skipping := false
	for _, line := range lines {
		if strings.Contains(line, begin) {
			skipping = true
			continue
		}
		if skipping {
			if strings.Contains(line, end) {
				skipping = false
			}
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func insertLines(lines []string, idx int, insert []string) []string {
	lines = append(lines[:idx], append(insert, lines[idx:]...)...)
	return lines
}

func leadingWhitespace(s string) string {
	return s[:len(s)-len(strings.TrimLeft(s, " \t"))]
}

func RestartMosDNSIfRunning(ctx context.Context, dataDir string) (bool, error) {
	pidFile := filepath.Join(dataDir, "data/mosdns.pid")
	pid := readPID(pidFile)
	if pid <= 0 || !processAlive(pid) {
		return false, nil
	}
	proc, err := os.FindProcess(pid)
	if err == nil {
		_ = proc.Signal(syscall.SIGTERM)
	}
	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) {
		if !processAlive(pid) {
			break
		}
		select {
		case <-ctx.Done():
			return false, ctx.Err()
		case <-time.After(200 * time.Millisecond):
		}
	}
	if processAlive(pid) && err == nil {
		_ = proc.Signal(syscall.SIGKILL)
	}
	_ = os.Remove(pidFile)
	bin := firstExisting(
		filepath.Join(dataDir, "data/binaries/mosdns/mosdns"),
		filepath.Join(dataDir, "data/binaries/mosdns/latest/mosdns"),
	)
	if _, err := os.Stat(bin); err != nil {
		return false, fmt.Errorf("mosdns was stopped but binary is not installed at %s", bin)
	}
	cfgDir := filepath.Join(dataDir, "configs/mosdns")
	if err := os.MkdirAll(filepath.Join(dataDir, "logs"), 0o755); err != nil {
		return false, err
	}
	stdout, err := os.OpenFile(filepath.Join(dataDir, "logs/mosdns.out.log"), os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return false, err
	}
	stderr, err := os.OpenFile(filepath.Join(dataDir, "logs/mosdns.err.log"), os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		_ = stdout.Close()
		return false, err
	}
	cmd := exec.CommandContext(context.Background(), bin, "start", "--dir", cfgDir)
	cmd.Dir = cfgDir
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	if runtime.GOOS != "windows" {
		cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	}
	if err := cmd.Start(); err != nil {
		_ = stdout.Close()
		_ = stderr.Close()
		return false, err
	}
	if err := os.WriteFile(pidFile, []byte(strconv.Itoa(cmd.Process.Pid)), 0o644); err != nil {
		return false, err
	}
	go func() {
		_ = cmd.Wait()
		_ = stdout.Close()
		_ = stderr.Close()
		_ = os.Remove(pidFile)
	}()
	return true, nil
}

func processAlive(pid int) bool {
	if pid <= 0 {
		return false
	}
	proc, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	if runtime.GOOS == "windows" {
		return true
	}
	return proc.Signal(syscall.Signal(0)) == nil
}

func firstExisting(paths ...string) string {
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return paths[0]
}
