"use client";

import { useState } from "react";
import { Database, Flame, Save, Trash2, X } from "lucide-react";
import { GlassSegmentedControl } from "@/components/liquid-glass/GlassSegmentedControl";
import { GlassSurface } from "@/components/liquid-glass/GlassSurface";
import { ModalViewport } from "@/components/liquid-glass/ModalViewport";
import { useMosdnsDashboardData } from "../../data";
import type { MosdnsCacheSystemPage, MosdnsWidgetSize } from "./model";

const options = [{ id: "stats", label: "统计" }, { id: "strategy", label: "策略" }, { id: "task", label: "任务" }, { id: "operations", label: "操作" }] as const;
function Switch({ checked, disabled, onClick }: { checked: boolean; disabled?: boolean; onClick: () => void }) { return <button type="button" role="switch" aria-checked={checked} disabled={disabled} onClick={onClick} className={`h-5 w-9 rounded-full p-0.5 transition disabled:opacity-50 ${checked ? "bg-emerald-500" : "bg-muted"}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${checked ? "translate-x-4" : ""}`} /></button>; }
export function taskProgressPercent(value: string) { const match = value.match(/(?:进度\s*)?(\d+(?:\.\d+)?)%/); return match ? Math.max(0, Math.min(100, Number(match[1]))) : null; }

export function MosdnsCacheSystemWidget({ activePage, onActivePageChange, size = "m" }: { activePage?: MosdnsCacheSystemPage; onActivePageChange?: (page: MosdnsCacheSystemPage) => void; size?: MosdnsWidgetSize }) {
  const data = useMosdnsDashboardData(["control"]); const [internal, setInternal] = useState<MosdnsCacheSystemPage>("stats"); const [activeDomain, setActiveDomain] = useState<"realIp" | "fakeIp" | "noV4" | "noV6" | null>(null); const page = activePage ?? internal;
  const setPage = (next: MosdnsCacheSystemPage) => { if (activePage === undefined) setInternal(next); onActivePageChange?.(next); };
  const statsPanel = <div className="grid grid-cols-2 gap-2">{([['realIp','RealIP',data.cacheData.stats.realIp],['fakeIp','FakeIP',data.cacheData.stats.fakeIp],['noV4','无 V4',data.cacheData.stats.noV4],['noV6','无 V6',data.cacheData.stats.noV6]] as const).map(([key,label,value]) => <button type="button" key={label} onClick={() => setActiveDomain(key)} className="rounded-xl bg-foreground/[.035] p-3 text-left transition hover:bg-foreground/[.06]"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold tabular-nums">{value.toLocaleString()}</p></button>)}<p className="col-span-2 text-center text-xs text-muted-foreground">总计 {data.cacheData.stats.totalDomains.toLocaleString()} 个域名</p></div>;
  const strategyPanel = <div className="space-y-2">{([['expiredCache1','过期缓存 1','国内/国外缓存（兼容/安全）'],['expiredCache2','过期缓存 2','全部缓存与 FakeIP']] as const).map(([key,label,description]) => <div key={key} className="flex items-center justify-between gap-3 rounded-xl bg-foreground/[.035] p-3"><div><p className="text-sm font-medium">{label}</p><p className="mt-0.5 text-xs text-muted-foreground">{description}</p></div><Switch checked={data.cacheData.strategy[key]} disabled={data.actionSaving} onClick={() => void data.toggleCacheStrategy(key)} /></div>)}</div>;
  const task = data.cacheData.scheduledTask;
  const status = data.cacheData.taskStatus; const progress = taskProgressPercent(status.lastRunRelative);
  const taskPanel = <div className="space-y-3"><div className="grid grid-cols-2 gap-2 rounded-xl bg-foreground/[.035] p-3 text-xs"><div><p className="text-muted-foreground">任务状态</p><p className="mt-1 font-medium">{status.currentStatus}</p></div><div><p className="text-muted-foreground">最后运行</p><p className="mt-1 font-medium tabular-nums">{status.lastRunTime}</p></div><div><p className="text-muted-foreground">进度 / 相对时间</p><p className="mt-1 font-medium tabular-nums">{status.lastRunRelative}</p></div><div><p className="text-muted-foreground">运行耗时</p><p className="mt-1 font-medium tabular-nums">{status.lastRunDuration}</p></div>{progress !== null ? <div className="col-span-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${progress}%` }} /></div> : null}{status.records?.length ? <div className="col-span-2 max-h-24 overflow-y-auto border-t border-border/30 pt-2">{status.records.map((record, index) => <p key={`${index}:${record}`} className="break-words py-0.5 font-mono text-[10px] text-muted-foreground">{record}</p>)}</div> : <p className="col-span-2 border-t border-border/30 pt-2 text-[10px] text-muted-foreground">暂无任务运行记录</p>}</div><div className="flex items-center justify-between rounded-xl bg-foreground/[.035] p-3"><span className="text-sm">启用定时任务</span><Switch checked={task.enabled} disabled={data.actionSaving} onClick={() => data.changeScheduledTask({ ...task, enabled: !task.enabled })} /></div><label className="block text-xs text-muted-foreground">首次执行时间<input type="datetime-local" value={task.firstRunTime === "-" ? "" : task.firstRunTime.replace(" ","T").slice(0,16)} onChange={(event) => data.changeScheduledTask({ ...task, firstRunTime: event.target.value.replace("T"," ") || "-" })} className="gary-field mt-1 h-9 w-full px-3 text-sm" /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs text-muted-foreground">间隔（分钟）<input type="number" min={1} value={task.intervalMinutes} onChange={(event) => data.changeScheduledTask({ ...task, intervalMinutes: Math.max(1, Number(event.target.value) || 1) })} className="gary-field mt-1 h-9 w-full px-3 text-sm" /></label><label className="text-xs text-muted-foreground">刷新天数<input type="number" min={1} value={task.refreshDays} onChange={(event) => data.changeScheduledTask({ ...task, refreshDays: Math.max(1, Number(event.target.value) || 1) })} className="gary-field mt-1 h-9 w-full px-3 text-sm" /></label></div><button type="button" disabled={data.actionSaving} onClick={() => void data.saveScheduledTask()} className="gary-glass-button w-full rounded-xl px-3 py-2 text-xs text-primary disabled:opacity-50"><Save className="h-3.5 w-3.5" />保存任务</button></div>;
  const clearDNSCache = () => { if (window.confirm("确定清空全部 MosDNS DNS 缓存吗？不会删除规则、订阅、配置或 Mihomo Fake-IP 数据库。")) void data.clearDNSCache(); };
  const clearGeneratedRules = () => { if (window.confirm("确定清空自动生成的分流规则吗？不会清理 DNS 缓存。")) void data.runCacheAction("clear"); };
  const operationsPanel = <div className="space-y-2"><button type="button" disabled={data.actionSaving} onClick={() => void data.runCacheAction("start")} className="gary-glass-button w-full justify-start rounded-xl px-3 py-3 text-xs"><Flame className="h-4 w-4 text-orange-500" />热更新缓存</button><button type="button" disabled={data.actionSaving} onClick={() => void data.runCacheAction("save")} className="gary-glass-button w-full justify-start rounded-xl px-3 py-3 text-xs"><Save className="h-4 w-4 text-primary" />保存缓存规则</button><button type="button" disabled={data.actionSaving} onClick={clearDNSCache} className="gary-glass-button w-full justify-start rounded-xl px-3 py-3 text-xs"><Database className="h-4 w-4 text-primary" />清空 DNS 缓存</button><button type="button" disabled={data.actionSaving} onClick={clearGeneratedRules} className="gary-glass-button w-full justify-start rounded-xl px-3 py-3 text-xs text-red-500"><Trash2 className="h-4 w-4" />清空生成规则</button><p className="text-xs leading-relaxed text-muted-foreground">两项清空操作互不影响；都不会删除订阅、配置或 Mihomo Fake-IP 数据库。</p></div>;
  const panels = { stats: statsPanel, strategy: strategyPanel, task: taskPanel, operations: operationsPanel };
  const domainModal = activeDomain ? <ModalViewport onClose={() => setActiveDomain(null)}><GlassSurface material="thick" role="dialog" aria-modal="true" className="flex max-h-[75dvh] w-full max-w-xl flex-col"><header className="flex items-center justify-between border-b border-border/40 px-4 py-3"><div><h3 className="text-sm font-semibold">缓存域名详情</h3><p className="text-xs text-muted-foreground">共 {(data.cacheDomains[activeDomain] || []).length} 条</p></div><button type="button" aria-label="关闭缓存域名详情" onClick={() => setActiveDomain(null)} className="gary-icon-button h-8 w-8 rounded-xl"><X className="h-4 w-4" /></button></header><div className="min-h-0 flex-1 overflow-y-auto px-4 py-2">{(data.cacheDomains[activeDomain] || []).map((row) => <div key={`${row.id}:${row.domain}`} className="flex gap-3 border-b border-border/30 py-2 text-xs last:border-0"><span className="shrink-0 font-mono text-muted-foreground">{row.id}</span><span className="min-w-0 flex-1 break-all font-mono">{row.domain}</span></div>)}{(data.cacheDomains[activeDomain] || []).length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">暂无域名数据</p> : null}</div></GlassSurface></ModalViewport> : null;
  if (size === "l") return <><div className="h-full min-h-0 overflow-y-auto"><div className="mb-3 flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Database className="h-4 w-4 text-primary" />缓存系统控制</span><span aria-live="polite" className={data.error ? "text-red-500" : "text-muted-foreground"}>{data.actionSaving ? "操作进行中…" : data.error || data.message}</span></div><div className="grid grid-cols-2 gap-4"><section><h4 className="mb-2 text-xs font-medium">统计</h4>{statsPanel}</section><section><h4 className="mb-2 text-xs font-medium">策略</h4>{strategyPanel}</section><section><h4 className="mb-2 text-xs font-medium">任务</h4>{taskPanel}</section><section><h4 className="mb-2 text-xs font-medium">操作</h4>{operationsPanel}</section></div></div>{domainModal}</>;
  return <><div className="flex h-full min-h-0 flex-col gap-3"><GlassSegmentedControl value={page} onChange={setPage} options={options.map((item) => ({ ...item }))} ariaLabel="缓存系统页面" className="grid w-full grid-cols-4" /><div className="min-h-0 flex-1 overflow-y-auto">{panels[page]}</div><p aria-live="polite" className={`min-h-4 text-[10px] ${data.error ? "text-red-500" : "text-muted-foreground"}`}>{data.actionSaving ? "操作进行中…" : data.error || data.message}</p></div>{domainModal}</>;
}
