import { useEffect, useMemo, useState } from "react";
import { ProxyEditorShell } from "./ProxyEditorShell";

export interface ProxyManualNodeDraft { mode: "links" | "yaml"; links: string; yaml: string; }
const EMPTY: ProxyManualNodeDraft = { mode: "links", links: "", yaml: "" };

export function ProxyManualNodeEditorDialog({ open, value, onClose, onValidate, onSave }: { open: boolean; value?: Partial<ProxyManualNodeDraft> | null; onClose: () => void; onValidate: (draft: ProxyManualNodeDraft) => Promise<string | void> | string | void; onSave: (draft: ProxyManualNodeDraft) => Promise<void> | void }) {
  const [draft, setDraft] = useState<ProxyManualNodeDraft>(EMPTY); const [initial, setInitial] = useState(EMPTY); const [busy, setBusy] = useState<"save" | "validate" | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { if (open) { const next = { ...EMPTY, ...(value || {}) }; setDraft(next); setInitial(next); setMessage(""); } }, [open, value]);
  const dirty = useMemo(() => JSON.stringify(draft) !== JSON.stringify(initial), [draft, initial]); const patch = <K extends keyof ProxyManualNodeDraft>(key: K, value: ProxyManualNodeDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const validate = async () => { setBusy("validate"); setMessage(""); try { setMessage((await onValidate(draft)) || "配置校验通过，可保存"); } catch (error) { setMessage(error instanceof Error ? error.message : "配置校验失败，未写入"); } finally { setBusy(null); } }; const save = async () => { setBusy("save"); setMessage(""); try { await onSave(draft); setInitial(draft); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败，未关闭编辑器"); } finally { setBusy(null); } };
  return <ProxyEditorShell open={open} title="管理自定义节点" description="支持分享链接和 Mihomo proxies YAML；保存会同步 msf_manual、系统设置及运行配置。" dirty={dirty} saving={busy === "save"} validating={busy === "validate"} validationMessage={message} onClose={onClose} onValidate={() => void validate()} onSave={() => void save()}><div className="space-y-4"><div className="flex rounded-xl bg-background/45 p-1">{(["links", "yaml"] as const).map((mode) => <button type="button" key={mode} onClick={() => patch("mode", mode)} className={`flex-1 rounded-lg px-3 py-2 text-xs font-medium ${draft.mode === mode ? "bg-primary/12 text-primary" : "text-muted-foreground"}`}>{mode === "links" ? "分享链接" : "YAML 节点列表"}</button>)}</div>{draft.mode === "links" ? <label className="block text-xs text-muted-foreground">每行一个分享链接<textarea value={draft.links} onChange={(event) => patch("links", event.target.value)} placeholder="vmess://… / ss://… / trojan://…" className="mt-1 min-h-28 w-full rounded-2xl bg-background/50 px-3 py-2 font-mono text-xs text-foreground outline-none focus:ring-2 focus:ring-primary/30" spellCheck={false} /></label> : <label className="block text-xs text-muted-foreground">Mihomo proxies YAML<textarea value={draft.yaml} onChange={(event) => patch("yaml", event.target.value)} className="mt-1 min-h-72 w-full rounded-2xl bg-background/50 px-3 py-2 font-mono text-xs outline-none focus:ring-2 focus:ring-primary/30" spellCheck={false} placeholder={'proxies:\n  - name: 手动节点\n    type: ss\n    server: example.com'} /></label>}<p className="rounded-xl bg-background/35 px-3 py-2 text-xs text-muted-foreground">会先生成候选配置并校验，失败时不写入、不重启；保存失败不会关闭弹窗。</p></div></ProxyEditorShell>;
}
